project:
  type: website

website:
  title: "Cloud-based Geospatial Analysis"
  sidebar:
    title: "Cloud-based Geospatial Analysis"
    logo: images/tnc_logo.png
    style: "docked"
    contents:
      - href: index.qmd
        text: "Setup"
      - href: notebooks/test.ipynb
        text: "test"
      - href: notebooks/1_Geopython.ipynb
        text: "Intro to Geospatial Python"
      - href: notebooks/1_ML_ANG.ipynb
        text: "Geospatial Machine learning"
        
execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

