project:
  type: website

website:
  title: "Python Teaching Notebooks"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "Home"
      - href: test2.qmd
        text: "qmd book"
      - href: notebooks/test3.ipynb
        text: "Notebooks dir"
      - href: test3.ipynb
        text: "Notebooks 4"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

